
jwt:
  secret: "[a-zA-Z0-9._]^+$Guidelinesrarsxyswbmcufdzb89797987forAlphabeticalArraNumeralsandOtherSymbo$"


server:
  port: 8081
#  error: # HTTP status - Not Found
#    whitelabel:
#      enabled: false

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/mesactualites?createDatabaseIfNotExist=true&useSSL=true
    password: root 
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create #create supprime la table a chaque demarrage
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false